title: Jean-Gabriel Young
email: jean-gabriel.young.1@ulaval.ca
description: > # this means to ignore newlines until "baseurl:"
  Personal website for the research work and blog posts of Jean-Gabriel Young
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.jgyoung.ca" # the base hostname & protocol for your site
twitter_username: _jgyou
github_username:  jg-you
include: ['crm2016']
plugins:
  - jekyll-feed

# Build settings
markdown: kramdown
theme: minima

